allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@scarf/scarf'
  - bcrypt
  - msgpackr-extract
  - prisma
  - unrs-resolver
